### ISSUE TITLE
reading points with -timeField is slow

### ISSUE THREAD

**Issue by henridf** [juttle/juttle-sqlite-adapter#5]
I'm trying to read about 300'000 points from sqlite. When i do: `read sqlite -table xyz`  I get all the points right away. 

If I do `read sqlite -table xyz -timeField "timefield"` the node process goes to 100% CPU and stays there for a long time (I killed it after about 20 minutes).

**Comment by VladVega** [comment]
@henridf any chance you can send me the data file so I can figure out what's happening in your particular case?

**Comment by VladVega** [comment]
Actually @henridf I've identified the problem. Working on it.

**Comment by VladVega** [comment]
This problem is now resolved.
